import type { CitationData } from './types.js';

export { generate } from './citation/index.js';

export function emptyCitationData(): CitationData {
  return {
    authors: [{ family: '', given: '' }],
    year: '',
    month: '',
    day: '',
    title: '',
    url: '',
    accessDate: '',
    quotePage: '',
    quotePages: '',
    quoteSection: '',
    quoteParagraph: '',
    timestamp: '',
    siteName: '',
    publisher: '',
    journal: '',
    volume: '',
    issue: '',
    pages: '',
    articleNumber: '',
    doi: '',
    edition: '',
    place: '',
    bookTitle: '',
    editors: [{ family: '', given: '' }],
    editorsText: '',
    translatorsText: '',
    originalYear: '',
    username: '',
    platform: '',
    description: '',
    postType: '',
    format: '',
    seriesTitle: '',
    season: '',
    episode: '',
    productionCompanies: '',
    writersText: '',
    directorsText: '',
    producersText: '',
    hostRole: '',
    reportNumber: '',
    institution: '',
    repository: '',
    jurisdiction: '',
    section: '',
    reporter: '',
    volumeLegal: '',
    startingPage: '',
    appendix: '',
    toolName: '',
  };
}
